#docker-compose.yml
version: "3.0"
services:
  user_service:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8080"
    restart: always
  note_service:
    build:
      context: "."
      dockerfile: dockerfile.noteservice
    depends_on:
      - db
    ports:
      - 8001:10003
    restart: always
  db:
    image: postgres 
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: root
    restart: always
