FROM golang:1.22.2-alpine3.18 AS builder

WORKDIR /usr/local/go/src/

ADD note_service/app/ /usr/local/go/src/

RUN go clean --modcache
RUN go build -mod=readonly -o app cmd/main/app.go

FROM alpine:3.18

COPY --from=builder /usr/local/go/src/app /
COPY --from=builder /usr/local/go/src/config.yml /

CMD ["/app"]